seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
  gpus: 1
  #gpus: 4
  #accelerator: ddp
  check_val_every_n_epoch: 2
  max_epochs: 400
model:
  d_model: 16
  growth_rate: 8
  num_layers: 4
  nhead: 4
  num_decoder_layers: 2
  dim_feedforward: 64
  dropout: 0.3
  beam_size: 5
  max_len: 200
  alpha: 1.0
  learning_rate: 1.0
  patience: 20
data:
  zipfile_path: ../bases/Base_soma_subtracao.zip
  test_year: test
  batch_size: 8
  num_workers: 5
