attention:
  attention_ch: 32
  attention_dim: 256
batch_size: 8
checkpoint: ''
checkpoint_dir: checkpoints
data_augmentation: 100
decoder:
  cell: GRU
  hidden_size: 64
  input_size: 64
  net: SAN_decoder
densenet:
  bottleneck: true
  growthRate: 16
  nDenseBlocks: 4
  ratio: 16
  reduction: 0.5
  three_layers: true
  use_dropout: false
#device: !!python/object/apply:torch.device
#- cuda
dropout: true
dropout_ratio: 0.5
encoder:
  input_channels: 1
  net: DenseNet
  out_channels: 120
epoches: 500
eps: 1e-6
eval_image_path: data/test_image.pkl
eval_label_path: data/test_label.pkl
experiment: SAN
finetune: false
gradient: 100
gradient_clip: true
hybrid_tree:
  threshold: 0.5
image_channel: 1
image_height: 200
image_width: 200
log_dir: logs
lr: 1
lr_decay: cosine
optimizer: Adadelta
optimizer_save: true
relu: true
resnet:
  conv1_stride: 1
struct_num: 7
train_image_path: data/train_image.pkl
train_label_path: data/train_label.pkl
use_label_mask: false
weight_decay: 1e-4
word_num: 24
word_path: data/word.txt
workers: 0
