# 实验名称
experiment: "SAN"

# 随机种子
seed: 20200814

# 训练参数
epoches: 1000
batch_size: 4
workers: 0
optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 10
eps: 1e-6
weight_decay: 1e-4
beta: 0.9
image_resize: True
#image_width: 200
#image_height: 200
image_width: 3200
image_height: 400
image_channel: 1
dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 训练数据
train_image_path: 'data/train_image.pkl'
train_label_path: 'data/train_label.pkl'
eval_image_path: 'data/test_image.pkl'
eval_label_path: 'data/test_label.pkl'

#word_path: 'data/word_1.5k_HME100K.txt'
word_path: 'data/word.txt'

# 选择encoder
encoder:
  net: DenseNet
  input_channels: 1
  out_channels: 684

resnet:
  conv1_stride: 1

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

# 使用的rnn cell
decoder:
  net: SAN_decoder
  cell: 'GRU'
  input_size: 128
  hidden_size: 128

# attention 参数
attention:
  attention_dim: 128

# hybrid tree
hybrid_tree:
  threshold: 0.5

# 训练权重存放路径
optimizer_save: True
checkpoint_dir: 'checkpoints'
finetune: False
#checkpoint: "checkpoints/SAN_2023-03-01-11-15_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600/SAN_2023-03-01-11-15_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600_WordRate-0.6223_structRate-0.9760_ExpRate-0.0617_10.pth"

# 7k imagens de treinamento
#checkpoint: "checkpoints/SAN_2023-03-10-10-22_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600/SAN_2023-03-10-10-22_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600_WordRate-0.7552_structRate-0.9972_ExpRate-0.1562_171.pth"

# 3k imagens de treinamento
#checkpoint: "checkpoints/SAN_2023-03-11-10-54_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600/SAN_2023-03-11-10-54_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600_WordRate-0.6722_structRate-0.9966_ExpRate-0.1483_171.pth"

# 1.5k imagens de treinamento
# checkpoint: "checkpoints/SAN_2023-03-14-07-05_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600/SAN_2023-03-14-07-05_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600_WordRate-0.3152_structRate-0.9787_ExpRate-0.0072_121.pth"

# Tentativa 1 - Base_soma_subtracao nossas_labels_sem_nenhum_overset
#checkpoint: "checkpoints/SAN_2023-03-18-07-54_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600/SAN_2023-03-18-07-54_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600_WordRate-0.4992_structRate-1.0000_ExpRate-0.2113_191.pth"

# Tentativa 2 - Base_soma_subtracao nossas_labels_sem_nenhum_overset
#checkpoint: "checkpoints/SAN_2023-03-20-07-22_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/SAN_2023-03-20-07-22_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200_WordRate-0.7647_structRate-1.0000_ExpRate-0.4000_441.pth"

# Tentativa 3 - test_nossas_labels_sem_oversets_enlinhados_e_vazaios
#checkpoint: "checkpoints/SAN_2023-03-25-09-52_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/SAN_2023-03-25-09-52_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200_WordRate-0.9395_structRate-1.0000_ExpRate-0.3347_961.pth"

# Tentativa 3 (erro de estrutura) - test_nossas_labels_sem_oversets_enlinhados_e_vazaios
#checkpoint: "checkpoints/SAN_2023-03-25-09-52_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/teste.pth"

# Tentativa 4
#checkpoint: "checkpoints/SAN_2023-03-31-11-37_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/SAN_2023-03-31-11-37_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200_195.pth"

# Tentativa 5 - em torno de 72% ExpRate no conjunto de teste
# checkpoint: "checkpoints/SAN_2023-03-31-14-28_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/SAN_2023-03-31-14-28_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200_135.pth"

# Tentativa 6
#checkpoint: "checkpoints/SAN_2023-04-03-09-14_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/SAN_2023-04-03-09-14_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200_-0.84-0.38_236.pth"

# Tentativa 7
checkpoint: "checkpoints/SAN_2023-04-04-08-30_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200/SAN_2023-04-04-08-30_Encoder-DenseNet_Decoder-SAN_decoder_max_size-200-200_-0.84-0.34_128.pth"

#checkpoint: "checkpoints/SAN_decoder/best.pth"


# tensorboard路径
log_dir: 'logs'
